/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:      Ship&balldata       (shbldata.h)               */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*   In deze file staan de declaraties van Ship&balldata               */
/*   Wanneer deze file geincluded wordt, krijgt met lees en schrijf    */
/*   rechten voor de Ship&balldatamanager                              */
/*                                                                     */
/* INPUT PAR:              geen                                        */
/* OUPUT PAR:              geen                                        */
/* DATUM:                  2 februari 1997                             */
/*=====================================================================*/

extern void calculate_shipanglenr(void);
extern void calculatepositions(void);