/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:	Beheert de enemydata 	(enemdata.cpp)	       */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*   In deze file staat de implementatie van de userdata               */
/*								       */
/* INPUT PAR:              geen                                        */
/* OUPUT PAR:              geen                                        */
/* DATUM:                  12 april 1997                               */
/*=====================================================================*/
#include        <conio.h>
#include        <iostream.h>

#include	"..\gamehead\gamehead.h"
#include        "!!forc~1\c\constant.h"
#include        "!!forc~1\c\enum.h"

#include        "!!forc~1\c\classen.h"

void Enemykogel::initkogels()
  {

  }


void Enemykogel::updatekogels()
  {

  }


void Enemykogel::drawkogels()
  {

  }


void Enemykogel::wipeoldkogels()
  {

  }
