/*=====================================================================*/
/*                                                                     */
/* PROGRAMMA NAAM:      Structure definitie         (struct.h)         */
/* AUTEUR:              Resourser                                      */
/* BESCHRIJVING:                                                       */
/*   In deze H-file staan alle constanten die nodig zijn voor          */
/*   het gehele programma                                              */
/*                                                                     */
/*                                                                     */
/*                                                                     */
/* DATUM:                  2 februari 1997                             */
/*=====================================================================*/

#define         P2I                            6.2831854

#define         Return                        13
#define         Spatie                        32

#define         cyclustime                     0.03
#define         halfcyclustime                 cyclustime / 2
#define         aantalangles                  24

#define         left                           1
#define         right                         -1

#define	       thrustforce		    		   500   // newton
#define	       mass		      					 10   // kilogram
#define         gravity                       10   // m/s^2

#define         stanglength                   10	// meter

#define         Xshipstartposition            20
#define         Yshipstartposition            20
#define         Xballstartposition            20
#define         Yballstartposition            10

//Xshipstartposition + stanglength